host_id: pve-wagmi
collector_url: http://100.88.84.81:5000/api/admin/logs/ingest

batch_interval: 5.0
batch_size: 50

sources:
  - name: pvedaemon
    type: journalctl
    target: pvedaemon

  - name: pveproxy
    type: journalctl
    target: pveproxy

  - name: pvestatd
    type: journalctl
    target: pvestatd

  - name: pve-firewall
    type: journalctl
    target: pve-firewall

  - name: nvidia-persistenced
    type: journalctl
    target: nvidia-persistenced

  - name: nvidia-powerd
    type: journalctl
    target: nvidia-powerd

  - name: zfs-zed
    type: journalctl
    target: zfs-zed

  - name: kernel
    type: journalctl
    target: ""
    extra_args: ["-k"]
